; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = signalgenerator

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:signalgenerator]
platform = espressif32
board = esp32dev
upload_port = COM5
monitor_port = COM5
build_src_filter =
    +<signalgenerator/>
    -<signalprocessing/>
    -<signalprocessing_maxrate/>


[env:signalprocessing]
platform = espressif32
board = heltec_wifi_lora_32_V3
upload_port = COM3
monitor_port = COM3
build_src_filter =
    +<signalprocessing/>
    -<signalgenerator/>
    -<signalprocessing_maxrate/>
lib_deps =
    kosme/arduinoFFT @ ^2.0.4


[env:signalprocessing_maxrate]
platform = espressif32
board = heltec_wifi_lora_32_V3
upload_port = COM3
monitor_port = COM3
framework = arduino
build_src_filter =
    +<signalprocessing_maxrate/>
    -<signalgenerator/>
    -<signalprocessing/>
